---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readxl)
library(tidyverse)
```

```{r}
rec <- read_excel("dados/Sankey Receitas por Fonte.xlsx", skip = 10)
des <- read_excel("dados/Sankey Despesas por Fonte.xlsx", skip = 10)

names(rec) <- c("nr", "fte", "fte_nome", "rec")
names(des) <- c("fte", "fte_nome", "nd", "des")

rec <- rec %>%
  group_by(nr) %>%
  mutate(rec = rec/1000000,
         subtot_rec = sum(rec),
         per_rec_fte = rec/sum(rec)) # calcula os % de distrib. de cada rec nas ftes

des <- des %>%
  group_by(fte) %>%
  mutate(des = des/1000000,
         per_fte_des = des/sum(des)) # calcula os % de distrib. de fte nas desps

matriz <- rec %>%
  full_join(des)

matriz <- matriz %>% 
  mutate(p = per_rec_fte * per_fte_des, # calcula o % de dist. de cada rec nas desps
         ramo = round(subtot_rec * p,0)) %>% # calcula então o tamanho de cada link, a
  group_by(nr,nd) %>%                        # partir do subtotal de cada receita
  summarise(p = sum(p),
            ramo = sum(ramo)) %>%
  select(nr,nd,p,ramo)

# relacao unica dos rotulos de receita e despesa:
rotulos <- c(unique(matriz$nr),unique(matriz$nd))

# conta os nós e gera sequencia numerica a partir de zero
num_nos <- length(rotulos)
nos <- 0:(num_nos-1)

# cria tabelinha para numerar os nos
tab_aux <- data.frame(rotulos, nos)

# incorpora os números dos nodes na matriz, para a receita... e para a despesa.
matriz <- matriz %>%
  left_join(tab_aux, by = c("nr" = "rotulos")) %>%   
  left_join(tab_aux, by = c("nd" = "rotulos"), suffix = c("_rec","_desp"))
  
```


```{r}
library(plotly)

p <- plot_ly(
    type = "sankey",
    orientation = "h",

    node = list(
      label = rotulos,
      #color = c("blue", "blue", "blue", "blue", "blue", "blue"),
      pad = 10,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = matriz$nos_rec,
      target = matriz$nos_desp,
      value =  matriz$ramo
      
    )
  ) %>% 
  layout(
    title = "Para onde vai o dinheiro?",
    font = list(
      size = 10
    )
)

p
```

Poderia criar vetores de cores na própria matriz, de maneira q, sempre q um nó fosse relacionado a dívida ou previdência (tanto receita, quanto despesa), usaria mesma cor.
